- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: install epel
  ansible.builtin.dnf:
    name:
    - epel-release
    state: latest
    install_weak_deps: false

- name: install basic soft
  ansible.builtin.dnf:
    name:
    - glibc-langpack-ru
    - openvpn
    - iperf3
    state: latest
    install_weak_deps: false

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled