---
- hosts: all
  become: true
  vars_files:
    - defaults/main.yml
  roles:
    - common

- hosts: server
  become: true
  gather_facts: no
  vars_files:
    - defaults/main.yml
  roles:
    - ovpn_server

- hosts: client
  become: true
  gather_facts: no
  vars_files:
    - defaults/main.yml
  roles:
    - ovpn_client
...