# файл создан на машине server командой: openvpn --genkey --secret /etc/openvpn/static.key
- name: copy static.key
  copy:
    src: static.key
    dest: /etc/openvpn/static.key
    owner: root
    group: root
    mode: 0600

- name: copy server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644

- name: create service unit
  copy:
    src: openvpn@.service
    dest: /etc/systemd/system/openvpn@.service
    owner: root
    group: root
    mode: 0644

- name: restart and enable service
  service: 
    name: openvpn@server
    state: restarted 
    enabled: yes